"""'funds-and-accounts'

Revision ID: 1fda6b01b4d4
Revises: 3013c26cfabb
Create Date: 2024-09-23 02:22:55.622018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fda6b01b4d4'
down_revision: Union[str, None] = '3013c26cfabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_account_id'), 'account', ['account_id'], unique=False)
    op.create_table('incoming_fund',
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_index(op.f('ix_incoming_fund_fund_id'), 'incoming_fund', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incoming_fund_fund_id'), table_name='incoming_fund')
    op.drop_table('incoming_fund')
    op.drop_index(op.f('ix_account_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
